import fs from "fs-extra";
import type { ProjectConfig } from "../types/project.js";

import {
  ProjectPathBoundary,
} from "../security/projectPathBoundary.js";

export async function createPackageJson(
  projectPath: string,
  config: ProjectConfig
): Promise<void> {
  const packageJson = {
    name: config.projectName.toLowerCase(),
    version: "0.1.0",
    private: true,
    description: `Project generated by Aurora CLI`,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start"
    }
  };

  const pathBoundary =
    new ProjectPathBoundary(
      projectPath
    );

  await fs.writeJson(
    pathBoundary.resolve(
      "package.json"
    ),
    packageJson,
    {
      spaces: 2
    }
  );
}
