import fs from "node:fs";
import { createProject } from "../services/project.js";
import { loadTemplateManifest } from "../services/manifest.js";
import { inspectProject } from "../projects/projectInspection.js";
import { readProjectMetadata } from "../projects/projectMetadata.js";
import { ProjectPathBoundary } from "../security/projectPathBoundary.js";
import { AuroraError } from "../errors/AuroraError.js";
import { ErrorCodes } from "../errors/errorCodes.js";
import { OperationPlanService, sha256 } from "../operations/operationPlanService.js";
import type { OperationPlan } from "../operations/operationPlan.js";
import { getSolutionPack } from "./solutionPacks.js";
import { parseSolutionState, type SolutionState } from "./solutionState.js";

const STATE_PATH = ".aurora/solution.json";
const HEALTH_PATH = "app/api/health/route.ts";
const HEALTH_CONTENT = [
  '// Generated by Aurora health capability v1.0.0.',
  'export const dynamic = "force-dynamic";', '',
  'export async function GET() {',
  '  return Response.json({ status: "ok" });', '}', '',
].join("\n");

export interface CreateSolutionOptions {
  readonly workspaceRoot?: string;
  readonly packageManager?: "npm" | "pnpm" | "yarn";
}
export interface CreatedSolution {
  readonly schemaVersion: 1;
  readonly root: string;
  readonly solution: SolutionState;
}

/** Offline, silent creation. Dependency installation and Git changes are separate. */
export async function createSolution(id: string, projectName: string,
  options: CreateSolutionOptions = {}): Promise<CreatedSolution> {
  const pack = getSolutionPack(id);
  const manager = options.packageManager ?? "npm";
  if (!pack.packageManagers.includes(manager) ||
      !/^[a-z0-9][a-z0-9._-]*$/u.test(projectName) || projectName.length > 214) {
    throw new AuroraError("Use a lowercase project name and a package manager supported by this starter.", {
      code: ErrorCodes.SOLUTION_NOT_SUPPORTED,
      suggestion: "Choose npm, pnpm, or yarn; use letters, numbers, periods, underscores, or hyphens in the name.",
    });
  }
  const manifest = await loadTemplateManifest(pack.template.id);
  if (manifest.version !== pack.template.version || manifest.framework !== pack.framework ||
      !manifest.language.includes(pack.language) || !manifest.packageManagers.includes(manager)) {
    throw new AuroraError("The bundled template does not match its solution descriptor.", {
      code: ErrorCodes.SOLUTION_NOT_SUPPORTED,
      suggestion: "Restore a complete trusted Aurora CLI installation; no project has been created.",
    });
  }
  const state = parseSolutionState({ schemaVersion: 1,
    solution: { id: pack.id, version: pack.version }, template: pack.template, capabilities: [] });
  const root = await createProject({ projectName, framework: pack.framework, language: pack.language,
    packageManager: manager, installDependencies: false, initializeGit: false }, {
    workspaceRoot: options.workspaceRoot, silent: true,
    additionalFiles: [{ relativePath: STATE_PATH, content: serializeState(state) }],
  });
  return { schemaVersion: 1, root: new ProjectPathBoundary(root).projectRoot, solution: state };
}

export interface PlanCapabilityOptions {
  readonly projectRoot: string;
  readonly service?: OperationPlanService;
}

/** Read only: produce a two-file plan; never install dependencies or run project scripts. */
export async function planCapability(id: string, options: PlanCapabilityOptions): Promise<OperationPlan> {
  const boundary = new ProjectPathBoundary(options.projectRoot);
  const report = inspectProject(boundary.projectRoot);
  if (!report.healthy || report.pendingTransactions !== 0 || !report.solution ||
      !report.project || !report.node) {
    throw capabilityError("A healthy Aurora solution project with no pending lifecycle transactions is required.");
  }
  let metadata;
  try { metadata = readProjectMetadata(boundary, STATE_PATH); }
  catch { throw capabilityError("Solution metadata cannot be read safely."); }
  if (!metadata) throw capabilityError("Solution metadata is missing.");
  const state = parseSolutionState(metadata.value);
  const pack = getSolutionPack(state.solution.id);
  if (state.solution.version !== pack.version || state.template.id !== pack.template.id ||
      state.template.version !== pack.template.version || report.project.framework !== pack.framework ||
      report.project.language !== pack.language || !report.node.dependencies.runtime.includes("next")) {
    throw capabilityError("Project identity does not match the supported bundled starter.");
  }
  const capability = pack.capabilities.find(candidate => candidate.id === id);
  if (!capability || id !== "health") throw capabilityError("This capability is not available for this solution.");
  if (state.capabilities.some(candidate => candidate.id === id)) {
    throw capabilityError("This capability is already recorded. Reinstalling or upgrading it is not enabled.");
  }
  // Never claim existing user files, even if their bytes happen to match generated output.
  try {
    fs.lstatSync(boundary.resolve("app/api/health"));
    throw capabilityError("The health endpoint directory already exists; your files have been left untouched.");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const updated = parseSolutionState({ ...state, capabilities: [
    ...state.capabilities, { id: capability.id, version: capability.version,
      files: [{ path: HEALTH_PATH, sha256: sha256(HEALTH_CONTENT) }] },
  ].sort((left, right) => left.id < right.id ? -1 : left.id > right.id ? 1 : 0) });
  const service = options.service ?? new OperationPlanService();
  const plan = await service.createFileWriteBatchPlan({
    projectRoot: boundary.projectRoot, intent: "capability.add-health",
    summary: "Add a liveness endpoint and record its Aurora capability identity.",
    files: [
      { relativePath: HEALTH_PATH, content: HEALTH_CONTENT,
        description: "Create /api/health, returning status ok while this app is running." },
      { relativePath: STATE_PATH, content: serializeState(updated),
        description: "Record health capability version and generated file digest.", mode: 0o600 },
    ],
  });
  // Bind to the metadata actually read, not a later, different snapshot.
  const route = plan.operations[0];
  const receipt = plan.operations[1];
  if (route?.kind !== "file.write" || route.expected.exists || receipt?.kind !== "file.write" ||
      !receipt.expected.exists || receipt.expected.sha256 !== metadata.sha256) {
    throw capabilityError("Project state changed during planning. Generate a fresh preview.");
  }
  return plan;
}

function serializeState(state: SolutionState): string { return `${JSON.stringify(state, null, 2)}\n`; }
function capabilityError(message: string): AuroraError {
  return new AuroraError(message, { code: ErrorCodes.CAPABILITY_PLAN_FAILED,
    suggestion: "Inspect the project and your files first. Use 'aurora create web-app <name>' for a supported new starter." });
}
