export const ErrorCodes = {
  TEMPLATE_NOT_FOUND:
    "TEMPLATE_NOT_FOUND",

  UNKNOWN_PLUGIN_ACTION:
    "UNKNOWN_PLUGIN_ACTION",

  UNKNOWN_CONFIGURATION_KEY:
    "UNKNOWN_CONFIGURATION_KEY",

  DOCTOR_CHECK_FAILED:
    "DOCTOR_CHECK_FAILED",

  UNSAFE_PROJECT_PATH:
    "UNSAFE_PROJECT_PATH",

  UNSAFE_PROCESS_REQUEST:
    "UNSAFE_PROCESS_REQUEST",

  PROCESS_EXECUTION_FAILED:
    "PROCESS_EXECUTION_FAILED",

  PROCESS_TIMEOUT:
    "PROCESS_TIMEOUT",

  PROCESS_ABORTED:
    "PROCESS_ABORTED",

  PROCESS_OUTPUT_LIMIT:
    "PROCESS_OUTPUT_LIMIT",

  INVALID_PACKAGE_MANIFEST:
    "INVALID_PACKAGE_MANIFEST",

  PACKAGE_INCOMPATIBLE:
    "PACKAGE_INCOMPATIBLE",

  PACKAGE_INTEGRITY_FAILED:
    "PACKAGE_INTEGRITY_FAILED",

  PACKAGE_REVOKED:
    "PACKAGE_REVOKED",

  INVALID_CONFIGURATION:
    "INVALID_CONFIGURATION",

  SECRET_IN_CONFIGURATION:
    "SECRET_IN_CONFIGURATION",

  CREDENTIAL_STORE_FAILED:
    "CREDENTIAL_STORE_FAILED",

  SECRET_AUDIT_FAILED:
    "SECRET_AUDIT_FAILED",

  DEVICE_AUTHORIZATION_FAILED:
    "DEVICE_AUTHORIZATION_FAILED",

  INVALID_OPERATION_PLAN:
    "INVALID_OPERATION_PLAN",

  OPERATION_APPROVAL_REQUIRED:
    "OPERATION_APPROVAL_REQUIRED",

  OPERATION_PLAN_EXPIRED:
    "OPERATION_PLAN_EXPIRED",

  OPERATION_PLAN_DRIFT:
    "OPERATION_PLAN_DRIFT",

  INVALID_OPERATION_REPORT:
    "INVALID_OPERATION_REPORT",

  PACKAGE_PERMISSION_DENIED:
    "PACKAGE_PERMISSION_DENIED",

  PACKAGE_EXECUTION_FAILED:
    "PACKAGE_EXECUTION_FAILED",

  PACKAGE_EXECUTION_TIMEOUT:
    "PACKAGE_EXECUTION_TIMEOUT",

  PACKAGE_OUTPUT_LIMIT:
    "PACKAGE_OUTPUT_LIMIT",

  INVALID_EXTENSION_MANIFEST:
    "INVALID_EXTENSION_MANIFEST",

  EXTENSION_PERMISSION_DENIED:
    "EXTENSION_PERMISSION_DENIED",

  EXTENSION_EXECUTION_FAILED:
    "EXTENSION_EXECUTION_FAILED",

  EXTENSION_TIMEOUT:
    "EXTENSION_TIMEOUT",

  EXTENSION_OUTPUT_LIMIT:
    "EXTENSION_OUTPUT_LIMIT",

  EXTENSION_CONCURRENCY_LIMIT:
    "EXTENSION_CONCURRENCY_LIMIT",
} as const;

export type AuroraErrorCode =
  typeof ErrorCodes[
    keyof typeof ErrorCodes
  ];
