export const ErrorCodes = {
  TEMPLATE_NOT_FOUND:
    "TEMPLATE_NOT_FOUND",

  UNKNOWN_PLUGIN_ACTION:
    "UNKNOWN_PLUGIN_ACTION",

  UNKNOWN_CONFIGURATION_KEY:
    "UNKNOWN_CONFIGURATION_KEY",

  DOCTOR_CHECK_FAILED:
    "DOCTOR_CHECK_FAILED",

  UNSAFE_PROJECT_PATH:
    "UNSAFE_PROJECT_PATH",

  UNSAFE_PROCESS_REQUEST:
    "UNSAFE_PROCESS_REQUEST",

  PROCESS_EXECUTION_FAILED:
    "PROCESS_EXECUTION_FAILED",

  PROCESS_TIMEOUT:
    "PROCESS_TIMEOUT",

  PROCESS_ABORTED:
    "PROCESS_ABORTED",

  PROCESS_OUTPUT_LIMIT:
    "PROCESS_OUTPUT_LIMIT",

  INVALID_PACKAGE_MANIFEST:
    "INVALID_PACKAGE_MANIFEST",

  PACKAGE_INCOMPATIBLE:
    "PACKAGE_INCOMPATIBLE",

  PACKAGE_INTEGRITY_FAILED:
    "PACKAGE_INTEGRITY_FAILED",

  PACKAGE_REVOKED:
    "PACKAGE_REVOKED",

  INVALID_CONFIGURATION:
    "INVALID_CONFIGURATION",

  SECRET_IN_CONFIGURATION:
    "SECRET_IN_CONFIGURATION",

  CREDENTIAL_STORE_FAILED:
    "CREDENTIAL_STORE_FAILED",

  SECRET_AUDIT_FAILED:
    "SECRET_AUDIT_FAILED",

  DEVICE_AUTHORIZATION_FAILED:
    "DEVICE_AUTHORIZATION_FAILED",
} as const;

export type AuroraErrorCode =
  typeof ErrorCodes[
    keyof typeof ErrorCodes
  ];
